version: '3.0'

services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=anirudh
      - POSTGRES_USER=postgres
      - POSTGRES_DB=anirudhdb
    volumes:
      - "anirudhvolume:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - sknetwork
  fastapi-app:
    volumes:
      - .:/fastapi
    build: .
    depends_on:
      - db
    networks:
      - sknetwork
    ports:
      - "8000:8000"

volumes:
  anirudhvolume:

networks:
  sknetwork: